{
 "title": "Image Inquisitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "image-inquisitor" },
   {
    "name": "last_successful_pod",
    "query": {
     "query": "query_result(max(kube_pod_completion_time{namespace=\"$namespace\"}) by (pod))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\",container=\"image-inquisitor\",pod=\"$last_successful_pod\"} | json | __error__ != \"JSONParserErr\" | kind=\"SummaryReport\""
    }
   ]
  },
  {
   "title": "Issues",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum_over_time({namespace=\"$namespace\",container=\"image-inquisitor\"} | json | __error__ != \"JSONParserErr\" | kind=\"SummaryReport\" | unwrap spec_report_issues_critical_count [$__auto])",
     "legendFormat": "🔴 Critical"
    },
    {
     "direction": "backward",
     "expr": "sum_over_time({namespace=\"$namespace\",container=\"image-inquisitor\"} | json | __error__ != \"JSONParserErr\" | kind=\"SummaryReport\" | unwrap spec_report_issues_high_count [$__auto])",
     "legendFormat": "🟠 High"
    },
    {
     "direction": "backward",
     "expr": "sum_over_time({namespace=\"$namespace\",container=\"image-inquisitor\"} | json | __error__ != \"JSONParserErr\" | kind=\"SummaryReport\" | unwrap spec_report_issues_medium_count [$__auto])",
     "legendFormat": "🟡 Medium"
    },
    {
     "direction": "backward",
     "expr": "sum_over_time({namespace=\"$namespace\",container=\"image-inquisitor\"} | json | __error__ != \"JSONParserErr\" | kind=\"SummaryReport\" | unwrap spec_report_issues_low_count [$__auto])",
     "legendFormat": "🟢 Low"
    },
    {
     "direction": "backward",
     "expr": "sum_over_time({namespace=\"$namespace\",container=\"image-inquisitor\"} | json | __error__ != \"JSONParserErr\" | kind=\"SummaryReport\" | unwrap spec_report_issues_unknown_count [$__auto])",
     "legendFormat": "⚪ Unknown"
    }
   ]
  },
  {
   "title": "Unique Repos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\",container=\"image-inquisitor\",pod=\"$last_successful_pod\"} | json | __error__ != \"JSONParserErr\" | kind=\"SummaryReport\"",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Last Scan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\",container=\"image-inquisitor\",pod=\"$last_successful_pod\"} | json | __error__ != \"JSONParserErr\" | kind=\"SummaryReport\"",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Unique Images",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\",container=\"image-inquisitor\",pod=\"$last_successful_pod\"} | json | __error__ != \"JSONParserErr\" | kind=\"SummaryReport\"",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Kubernetes Sources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\",container=\"image-inquisitor\",pod=\"$last_successful_pod\"} | json | __error__ != \"JSONParserErr\" | kind=\"SummaryReport\"",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Image Inventory",
   "type": "table",
   "gridPos": { "h": 31, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\",container=\"image-inquisitor\",pod=\"$last_successful_pod\"} | \r\n    json | \r\n    __error__ != \"JSONParserErr\" | \r\n    kind=\"ImageSummaryReport\"",
     "maxLines": 1
    }
   ]
  }
 ]
}